// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvbcifexjkoilmneuhrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2YmNpZmV4amtvaWxtbmV1aHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzc1NzAsImV4cCI6MjA2OTkxMzU3MH0.IV4xx-MJaSMJh67uMgH02uOB9ei3dDYmBsMB3iAONNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});